2025-05-03 21:33:33 +0000 - dagster - DEBUG - etl_daily_job - ae5f02b4-7acb-41aa-b788-7642c6df59c3 - 9477 - LOGS_CAPTURED - Started capturing logs in process (pid: 9477).
2025-05-03 21:33:33 +0000 - dagster - DEBUG - etl_daily_job - ae5f02b4-7acb-41aa-b788-7642c6df59c3 - 9477 - raw_wind_power_data - STEP_START - Started execution of step "raw_wind_power_data".
2025-05-03 21:33:33 +0000 - dagster - ERROR - etl_daily_job - ae5f02b4-7acb-41aa-b788-7642c6df59c3 - 9477 - raw_wind_power_data - STEP_FAILURE - Execution of step "raw_wind_power_data" failed.

dagster._core.errors.DagsterInvariantViolationError: Cannot access partition_key for a non-partitioned run

Stack Trace:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 506, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 189, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 187, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 156, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/opt/dagster/app/dagster_defs/__init__.py", line 43, in raw_wind_power_data
    partition_date_str = context.asset_partition_key_for_output()
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/decorator_utils.py", line 195, in wrapped_with_pre_call_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/context/asset_execution_context.py", line 216, in asset_partition_key_for_output
    return self.op_execution_context.asset_partition_key_for_output(output_name=output_name)
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/decorator_utils.py", line 195, in wrapped_with_pre_call_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/context/op_execution_context.py", line 677, in asset_partition_key_for_output
    return self._step_execution_context.asset_partition_key_for_output(output_name)
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/context/system.py", line 1150, in asset_partition_key_for_output
    start, end = self.asset_partition_key_range_for_output(output_name)
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/context/system.py", line 1145, in asset_partition_key_range_for_output
    return self.partition_key_range
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/context/system.py", line 1007, in partition_key_range
    raise DagsterInvariantViolationError(

